notifications:
  email: false

sudo: required

language: python
python:
  - "3.4"

before_install:
  - export TEXINPUTS=:./:$TEXMF/tex/{$progname,generic,}//:/usr/local/texlive/texmf-local//:/usr/local/texlive/2016/texmf-var//:/usr/local/texlive/2016/texmf-config//:/usr/local/texlive/2016/texmf-dist//:/usr/local/share/texmf//:/var/lib/texmf//

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - mkdir -p $HOME/tmp/sphinx
  - curl -L -O http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xvf install-tl-unx.tar.gz
  - cd install-tl*
  - sudo ./install-tl -scheme scheme-basic --repository http://mirror.ctan.org/systems/texlive/tlnet/ < ../InputAction_I_Enter.txt
  - sudo /usr/local/texlive/2016/bin/x86_64-linux/tlmgr update --self --all
  - sudo /usr/local/texlive/2016/bin/x86_64-linux/tlmgr install latexmk collection-luatex collection-langjapanese collection-fontsrecommended filehook type1cm mdframed needspace
  - ls -l /usr/local/texlive/2016/bin/x86_64-linux
  - ls -l /usr/local/texlive/2016/bin/x86_64-linux/latex
  - apt-cache search titlesec | grep tex
  - apt-cache search cmap | grep tex
  - sudo apt-get install texlive-latex-extra texlive-latex-recommended texlive-formats-extra
  - sudo mktexlsr
  - sudo find / -name "texmf.cnf"
  - sudo find / -name "ls-R"
  - sudo find / -name "cmap"
  - sudo find / -name "titlesec"
  - kpsewhich titlesec.sty  
  - kpsewhich cmap.sty
  
  - cd ..

before_script:
  - ERROR_LOG_FILE=$HOME/tmp/sphinx/build-error.log

script:
  - sh -c ./build-pdf.sh 2> $ERROR_LOG_FILE
  - sh -c ./build-pdf_en.sh >> $ERROR_LOG_FILE
  - cat $ERROR_LOG_FILE

after_script:
  - ERROR_COUNT=`grep ERROR $ERROR_LOG_FILE | wc -l`
  - WARNING_COUNT=`grep WARNING $ERROR_LOG_FILE | wc -l`
  - if [[ $ERROR_COUNT -ne 0 || $WARNING_COUNT -ne 0 ]]; then echo "Build is failed. Please fix errors or warnings."; exit 1; fi

