sudo: required
language: python
python:
  - "3.4"

before_install:
  - export PATH=$PATH:/bin/sh

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - mkdir -p $HOME/tmp/sphinx
  - curl -L -O http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xvf install-tl-unx.tar.gz
  - cd install-tl*
  - pwd
  - sudo ./install-tl --repository http://mirror.ctan.org/systems/texlive/tlnet/ < ../test.txt

before_script:
  - ERROR_LOG_FILE=$HOME/tmp/sphinx/build-error.log

script:
  - sh ./build-pdf.sh 2> $ERROR_LOG_FILE
  - sh ./build-pdf_en.sh 2>> $ERROR_LOG_FILE
  - cat $ERROR_LOG_FILE

after_script:
  - ERROR_COUNT=`grep ERROR $ERROR_LOG_FILE | wc -l`
  - WARNING_COUNT=`grep WARNING $ERROR_LOG_FILE | wc -l`
  - if [[ $ERROR_COUNT -ne 0 || $WARNING_COUNT -ne 0 ]]; then echo "Build is failed. Please fix errors or warnings."; exit 1; fi
