notifications:
  email: false

sudo: required

language: python
python:
  - "3.4"

before_install:
  - export PATH=/etc/texmf/dvipdfmx:/usr/share/texmf-texlive/fonts/map/dvipdfmx:/usr/local/texlive/2016/texmf-dist/fonts/cmap/dvipdfmx:/usr/share/texmf-texlive/fonts/cmap/dvipdfmx:$PATH:/usr/local/texlive/2016/bin/x86_64-linux
  - export TEXINPUTS=:./:$TEXMF/tex/{$progname,generic,}//:/usr/share/texmf-texlive/tex/latex//
  - echo $PATH

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - mkdir -p $HOME/tmp/sphinx
  - curl -L -O http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xvf install-tl-unx.tar.gz
  - cd install-tl*
  - sudo ./install-tl -scheme scheme-basic --repository http://mirror.ctan.org/systems/texlive/tlnet/ < ../InputAction_I_Enter.txt
  - sudo /usr/local/texlive/2016/bin/x86_64-linux/tlmgr update --self --all
  - sudo /usr/local/texlive/2016/bin/x86_64-linux/tlmgr install latexmk collection-luatex collection-langjapanese collection-fontsrecommended
  - sudo apt-get install texlive-latex-extra texlive-latex-recommended texlive-formats-extra
  - sudo mktexlsr
  - sudo which dvipdfmx
  - sudo find / -name "dvipdfmx"
  - cd ..

before_script:
  - ERROR_LOG_FILE=$HOME/tmp/sphinx/build-error.log

script:
#  - sh ./build-html.sh 2> $ERROR_LOG_FILE
#  - sh ./build-html_en.sh 2>> $ERROR_LOG_FILE
  - sh ./build-pdf.sh < ./InputAction_Enter.txt 2>> $ERROR_LOG_FILE
  - sh ./build-pdf_en.sh < ./InputAction_Enter.txt 2>> $ERROR_LOG_FILE
#  - sh ./build-pdf.sh < ./InputAction_Enter.txt
#  - sh ./build-pdf_en.sh < ./InputAction_Enter.txt
  - cat $ERROR_LOG_FILE

after_script:
  - ERROR_COUNT=`grep ERROR $ERROR_LOG_FILE | wc -l`
  - WARNING_COUNT=`grep WARNING $ERROR_LOG_FILE | wc -l`
  - if [[ $ERROR_COUNT -ne 0 || $WARNING_COUNT -ne 0 ]]; then echo "Build is failed. Please fix errors or warnings."; exit 1; fi

